### ISSUE TITLE
stopped working. images are all black with light style

### ISSUE THREAD

**Issue by jimmymjing** [Gamua/Starling-Extension-Dynamic-Lighting#4]
Hello, suddenly this dynamic lighting style stopped working. These images with Light style turn all black and no light sources would affect these images...

Here's my post in the forum: https://forum.starling-framework.org/d/22943-dynamic-lighting-stopped-working

**Comment by PrimaryFeather** [comment]
Did you find a solution for the issue?

**Comment by jimmymjing** [comment]
Sorry I missed your reply! It's my own fault which has nothing to do with the API!
